version: '3.7'
services:
  test:
    build: .
    command: sbt test
    volumes:
      - .:/app
    ports:
      - 8081:8081
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: users